name: Release Drafter

on:
  push:
    branches: [ master ]

categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
exclude-labels:
  - 'skip-changelog'
template: |
  ## What’s Changed

  $CHANGES